spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devtools
    username: devtools
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
